version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./autenticacao:/autenticacao
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"